# Generated by Django 5.1 on 2024-08-21 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory1', '0004_item5_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='C:\\Users\\hp\\Desktop\\ansh\\python training\\week6\\inventory\\inventory1\\img')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory1.item5')),
            ],
        ),
    ]
